"""
src/dashboard/components.py
---------------------------

Reusable UI components for the CementAI dashboard.
"""

import streamlit as st

# -------------------------------
# KPI Display Component
# -------------------------------
def display_kpis(kpi_dict: dict):
    """
    Display key performance indicators in dashboard.
    Args:
        kpi_dict (dict): {"SPC": 85, "TSR": 12, "Downtime": 3}
    """
    st.subheader("Key Performance Indicators (KPIs)")
    cols = st.columns(len(kpi_dict))
    for i, (key, value) in enumerate(kpi_dict.items()):
        cols[i].metric(label=key, value=value)

# -------------------------------
# Process Parameters Table
# -------------------------------
def display_parameters_table(df):
    """
    Display DataFrame of plant parameters.
    Args:
        df (pd.DataFrame)
    """
    st.subheader("Plant Process Parameters")
    st.dataframe(df)

# -------------------------------
# Recommendations Display
# -------------------------------
def display_recommendations(recommendations: dict):
    """
    Display recommendations generated by AI.
    Args:
        recommendations (dict)
    """
    st.subheader("Process Recommendations")
    for stage, rec in recommendations.items():
        st.write(f"**{stage}**: {rec.get('action','No recommendation')}")
